### ISSUE TITLE
#29 / Add hotkeys

### ISSUE THREAD

**Issue by macskay** [pasteit/pasteit#3]
Refheap offered some Hotkeys, which can also be seen in the help bubble. Those hotkeys should return.

- [x] Setup keybindings with placeholder functions

When creating a paste:
- [x] CTRL+Enter => Create Paste
- [ ] ALT+W => Toggle Word Wrap

When viewing a paste:
 - [ ] ALT+G => Go to a line
 - [ ] ALT+CTRL+E => Edit the paste
 - [ ] ALT+R => Show raw code

URL options (when creating):
 - [ ] ?lang=Javascript to default to JS
 
URL options (when viewing):
 - [ ] #L-N Jump to line number N

**Comment by ghost** [comment]
What specific hotkeys do you want?

**Comment by macskay** [comment]
See description

**Comment by macskay** [comment]
Still wip with #7

**Comment by ghost** [comment]
What is missing?

**Comment by ghost** [comment]
ping

**Comment by macskay** [comment]
see the pr, i've added comment there 
https://github.com/macskay/pasteit/pull/7#issuecomment-335050586

**Comment by macskay** [comment]
This can be closed, due to the decision of getting rid off hotkeys and mousetrap.
