### ISSUE TITLE
#43 / Enable continuous deployment

### ISSUE THREAD

**Issue by ghost** [pasteit/pasteit#41]
To deploy the software, maintainers should only be required to push to the master branch. This should cause a suite of tests to be run that verifies the system is working as expected, then if the tests pass, automatically deploys the changes to the production server environment.

Pushing to the develop branch should have the same effect on the development environment.

**Comment by macskay** [comment]
There is a bamboo instance and I will add a job in there for that. I'll give you access to the project. Please login to https://bamboo.gothax.net with your ldap credentials, so your account gets created.

**Comment by macskay** [comment]
Done. Job runs every night at 12 AM CEST and after a max. of 30 seconds after develop has been pushed to. Job can be found at: https://bamboo.gothax.net/browse/PAS-DEV
