### ISSUE TITLE
#44 / Author contribution guidelines wiki

### ISSUE THREAD

**Issue by ghost** [pasteit/pasteit#42]
Write a Wiki page documenting how to contribute to pasteit. It should cover the fork, branch, pull request process, coding conventions and testing requirements.

Follow the best practices outlined here: https://github.com/blog/1184-contributing-guidelines

**Comment by macskay** [comment]
Added in wiki. CONTRIBUTE.md still needed

**Comment by macskay** [comment]
@wkmanire: Giving this to your for rephrasing
